openapi: 3.1.0
info:
  contact:
    email: support@konghq.com
    name: Kong Inc
    url: https://konghq.com
  description: 'OpenAPI 3.0 spec for Kong Gateway''s Admin API.


    You can learn more about Kong Gateway at [developer.konghq.com](https://developer.konghq.com).

    Give Kong a star at the [Kong/kong](https://github.com/kong/kong) repository.'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Kong Enterprise Admin ACLs MTLS-auth credentials API
  version: 3.14.0
servers:
- description: Default Admin API URL
  url: '{protocol}://{hostname}:{port}{path}'
  variables:
    hostname:
      default: localhost
      description: Hostname for Kong's Admin API
    path:
      default: /
      description: Base path for Kong's Admin API
    port:
      default: '8001'
      description: Port for Kong's Admin API
    protocol:
      default: http
      description: Protocol for requests to Kong's Admin API
      enum:
      - http
      - https
security:
- adminToken: []
tags:
- name: MTLS-auth credentials
paths:
  /{workspace}/consumers/{ConsumerIdForNestedEntities}/mtls-auth:
    post:
      x-speakeasy-entity-operation:
        terraform-datasource: null
        terraform-resource: MTLSAuth#create
      operationId: create-mtls-auth-with-consumer
      summary: Create a new MTLS-auth credential associated with a Consumer
      description: Create a new MTLS-auth credential associated with a Consumer
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities'
      - $ref: '#/components/parameters/Workspace'
      requestBody:
        description: Description of new MTLS-auth credential for creation
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MTLSAuthWithoutParents'
      responses:
        '201':
          description: Successfully created MTLS-auth credential
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MTLSAuth'
      tags:
      - MTLS-auth credentials
  /{workspace}/consumers/{ConsumerIdForNestedEntities}/mtls-auth/{MTLSAuthId}:
    delete:
      x-speakeasy-entity-operation:
        terraform-datasource: null
        terraform-resource: MTLSAuth#delete
      operationId: delete-mtls-auth-with-consumer
      summary: Delete a a MTLS-auth credential associated with a Consumer
      description: Delete a a MTLS-auth credential associated with a Consumer using ID.
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities'
      - $ref: '#/components/parameters/MTLSAuthId'
      - $ref: '#/components/parameters/Workspace'
      responses:
        '204':
          description: Successfully deleted MTLS-auth credential or the resource didn't exist
      tags:
      - MTLS-auth credentials
    get:
      x-speakeasy-entity-operation:
        terraform-datasource: null
        terraform-resource: MTLSAuth#read
      operationId: get-mtls-auth-with-consumer
      summary: Get a MTLS-auth credential associated with a Consumer
      description: Get a MTLS-auth credential associated with a Consumer using ID.
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities'
      - $ref: '#/components/parameters/MTLSAuthId'
      - $ref: '#/components/parameters/Workspace'
      responses:
        '200':
          description: Successfully fetched MTLS-auth credential
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MTLSAuth'
        '404':
          description: Resource does not exist
      tags:
      - MTLS-auth credentials
  /v2/control-planes/{controlPlaneId}/core-entities/consumers/{ConsumerIdForNestedEntities}/mtls-auth:
    parameters:
    - $ref: '#/components/parameters/controlPlaneId'
    get:
      operationId: list-mtls-auth-with-consumer
      summary: List all MTLS-auth credentials associated with a Consumer
      description: List all MTLS-auth credentials associated with a Consumer
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities_2'
      - $ref: '#/components/parameters/PaginationSize'
      - $ref: '#/components/parameters/PaginationOffset'
      - $ref: '#/components/parameters/PaginationTagsFilter'
      responses:
        '200':
          description: A successful response listing MTLS-auth credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/MTLSAuth_2'
                  next:
                    $ref: '#/components/schemas/PaginationNextResponse'
                  offset:
                    $ref: '#/components/schemas/PaginationOffsetResponse'
      tags:
      - MTLS-auth credentials
    post:
      operationId: create-mtls-auth-with-consumer
      summary: Create a new MTLS-auth credential associated with a Consumer
      description: Create a new MTLS-auth credential associated with a Consumer
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities_2'
      requestBody:
        description: Description of new MTLS-auth credential for creation
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MTLSAuthWithoutParents_2'
      responses:
        '201':
          description: Successfully created MTLS-auth credential
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MTLSAuth_2'
      tags:
      - MTLS-auth credentials
  /v2/control-planes/{controlPlaneId}/core-entities/consumers/{ConsumerIdForNestedEntities}/mtls-auth/{MTLSAuthId}:
    parameters:
    - $ref: '#/components/parameters/controlPlaneId'
    delete:
      operationId: delete-mtls-auth-with-consumer
      summary: Delete a a MTLS-auth credential associated with a Consumer
      description: Delete a a MTLS-auth credential associated with a Consumer using ID.
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities_2'
      - $ref: '#/components/parameters/MTLSAuthId_2'
      responses:
        '204':
          description: Successfully deleted MTLS-auth credential or the resource didn't exist
      tags:
      - MTLS-auth credentials
    get:
      operationId: get-mtls-auth-with-consumer
      summary: Get a MTLS-auth credential associated with a Consumer
      description: Get a MTLS-auth credential associated with a Consumer using ID.
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities_2'
      - $ref: '#/components/parameters/MTLSAuthId_2'
      responses:
        '200':
          description: Successfully fetched MTLS-auth credential
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MTLSAuth_2'
        '404':
          description: Resource does not exist
      tags:
      - MTLS-auth credentials
    put:
      operationId: upsert-mtls-auth-with-consumer
      summary: Upsert a MTLS-auth credential associated with a Consumer
      description: Create or Update a MTLS-auth credential associated with a Consumer using ID.
      parameters:
      - $ref: '#/components/parameters/ConsumerIdForNestedEntities_2'
      - $ref: '#/components/parameters/MTLSAuthId_2'
      requestBody:
        description: Description of the MTLS-auth credential
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MTLSAuthWithoutParents_2'
      responses:
        '200':
          description: Successfully upserted MTLS-auth credential
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MTLSAuth_2'
      tags:
      - MTLS-auth credentials
  /v2/control-planes/{controlPlaneId}/core-entities/mtls-auths:
    parameters:
    - $ref: '#/components/parameters/controlPlaneId'
    get:
      operationId: list-mtls-auth
      summary: List all MTLS-auth credentials
      description: List all MTLS-auth credentials
      parameters:
      - $ref: '#/components/parameters/PaginationSize'
      - $ref: '#/components/parameters/PaginationOffset'
      - $ref: '#/components/parameters/PaginationTagsFilter'
      responses:
        '200':
          description: A successful response listing MTLS-auth credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/MTLSAuth_2'
                  next:
                    $ref: '#/components/schemas/PaginationNextResponse'
                  offset:
                    $ref: '#/components/schemas/PaginationOffsetResponse'
        '401':
          $ref: '#/components/responses/HTTP401Error'
      tags:
      - MTLS-auth credentials
  /v2/control-planes/{controlPlaneId}/core-entities/mtls-auths/{MTLSAuthId}:
    parameters:
    - $ref: '#/components/parameters/MTLSAuthId_2'
    - $ref: '#/components/parameters/controlPlaneId'
    get:
      operationId: get-mtls-auth
      summary: Get a MTLS-auth credential
      description: Get a MTLS-auth credential using ID.
      responses:
        '200':
          description: Successfully fetched MTLS-auth credential
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MTLSAuth_2'
        '401':
          $ref: '#/components/responses/HTTP401Error'
        '404':
          description: Resource does not exist
      tags:
      - MTLS-auth credentials
components:
  parameters:
    ConsumerIdForNestedEntities_2:
      description: Consumer ID for nested entities
      example: ''
      in: path
      name: ConsumerIdForNestedEntities
      required: true
      schema:
        type: string
    PaginationSize:
      description: Number of resources to be returned.
      in: query
      name: size
      schema:
        type: integer
        default: 100
        maximum: 1000
        minimum: 1
    MTLSAuthId_2:
      description: ID of the MTLS-auth credential to lookup
      example: ''
      in: path
      name: MTLSAuthId
      required: true
      schema:
        type: string
    Workspace:
      description: The name of the workspace
      in: path
      name: workspace
      required: true
      schema:
        type: string
        example: team-payments
        default: default
    PaginationOffset:
      allowEmptyValue: true
      description: Offset from which to return the next set of resources. Use the value of the 'offset' field from the response of a list operation as input here to paginate through all the resources
      in: query
      name: offset
      schema:
        type: string
    ConsumerIdForNestedEntities:
      description: Consumer ID for nested entities
      example: ''
      in: path
      name: ConsumerIdForNestedEntities
      required: true
      schema:
        type: string
      x-speakeasy-name-override: consumer_id
    MTLSAuthId:
      description: ID of the MTLS-auth credential to lookup
      example: ''
      in: path
      name: MTLSAuthId
      required: true
      schema:
        type: string
      x-speakeasy-match: id
    controlPlaneId:
      name: controlPlaneId
      in: path
      required: true
      schema:
        type: string
        format: uuid
        example: 9524ec7d-36d9-465d-a8c5-83a3c9390458
      description: The UUID of your control plane. This variable is available in the Konnect manager.
      x-speakeasy-param-force-new: true
    PaginationTagsFilter:
      allowEmptyValue: true
      description: A list of tags to filter the list of resources on. Multiple tags can be concatenated using ',' to mean AND or using '/' to mean OR.
      example: tag1,tag2
      in: query
      name: tags
      schema:
        type: string
  schemas:
    PaginationOffsetResponse:
      description: Offset is used to paginate through the API. Provide this value to the next list operation to fetch the next page
      type: string
    GatewayUnauthorizedError:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
      required:
      - message
      - status
    MTLSAuth_2:
      type: object
      properties:
        ca_certificate:
          type: object
          properties:
            id:
              type: string
          x-foreign: true
        consumer:
          type: object
          nullable: true
          properties:
            id:
              type: string
          x-foreign: true
        created_at:
          description: Unix epoch when the resource was created.
          type: integer
          nullable: true
        id:
          description: A string representing a UUID (universally unique identifier).
          type: string
          nullable: true
        subject_name:
          type: string
        tags:
          description: A set of strings representing tags.
          type: array
          items:
            description: A string representing a tag.
            type: string
          nullable: true
      example:
        ca_certificate:
          id: b2f34145-0343-41a4-9602-4c69dec2f260
        consumer:
          id: 84a73fb8-50fc-44a7-a4d5-aa17728ee83f
        id: b2f34145-0343-41a4-9602-4c69dec2f269
        subject_name: CA_Subject_Name
      additionalProperties: false
      required:
      - subject_name
    MTLSAuth:
      x-speakeasy-entity: MTLSAuth
      type: object
      properties:
        ca_certificate:
          type: object
          properties:
            id:
              type: string
          x-foreign: true
        consumer:
          type: object
          nullable: true
          properties:
            id:
              type: string
          x-foreign: true
          x-speakeasy-terraform-ignore: true
        created_at:
          description: Unix epoch when the resource was created.
          type: integer
          nullable: true
        id:
          description: A string representing a UUID (universally unique identifier).
          type: string
          nullable: true
        subject_name:
          type: string
        tags:
          description: A set of strings representing tags.
          type: array
          items:
            description: A string representing a tag.
            type: string
          nullable: true
      example:
        ca_certificate:
          id: b2f34145-0343-41a4-9602-4c69dec2f260
        consumer:
          id: 84a73fb8-50fc-44a7-a4d5-aa17728ee83f
        id: b2f34145-0343-41a4-9602-4c69dec2f269
        subject_name: CA_Subject_Name
      additionalProperties: false
      required:
      - subject_name
    MTLSAuthWithoutParents_2:
      type: object
      properties:
        ca_certificate:
          type: object
          properties:
            id:
              type: string
          x-foreign: true
        consumer:
          type: object
          nullable: true
          properties:
            id:
              type: string
          x-foreign: true
        created_at:
          description: Unix epoch when the resource was created.
          type: integer
          nullable: true
        id:
          description: A string representing a UUID (universally unique identifier).
          type: string
          nullable: true
        subject_name:
          type: string
        tags:
          description: A set of strings representing tags.
          type: array
          items:
            description: A string representing a tag.
            type: string
          nullable: true
      example:
        ca_certificate:
          id: b2f34145-0343-41a4-9602-4c69dec2f260
        id: b2f34145-0343-41a4-9602-4c69dec2f269
        subject_name: CA_Subject_Name
      additionalProperties: false
      required:
      - subject_name
    PaginationNextResponse:
      description: URI to the next page (may be null)
      type: string
    MTLSAuthWithoutParents:
      x-speakeasy-entity: MTLSAuth
      type: object
      properties:
        ca_certificate:
          type: object
          properties:
            id:
              type: string
          x-foreign: true
        consumer:
          type: object
          nullable: true
          properties:
            id:
              type: string
          x-foreign: true
          x-speakeasy-terraform-ignore: true
        created_at:
          description: Unix epoch when the resource was created.
          type: integer
          nullable: true
        id:
          description: A string representing a UUID (universally unique identifier).
          type: string
          nullable: true
        subject_name:
          type: string
        tags:
          description: A set of strings representing tags.
          type: array
          items:
            description: A string representing a tag.
            type: string
          nullable: true
      example:
        ca_certificate:
          id: b2f34145-0343-41a4-9602-4c69dec2f260
        id: b2f34145-0343-41a4-9602-4c69dec2f269
        subject_name: CA_Subject_Name
      additionalProperties: false
      required:
      - subject_name
  responses:
    HTTP401Error:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GatewayUnauthorizedError'
  securitySchemes:
    adminToken:
      in: header
      name: Kong-Admin-Token
      type: apiKey
externalDocs:
  description: Documentation for Kong Gateway and its APIs
  url: https://developer.konghq.com
