openapi: 3.1.0
info:
  contact:
    email: support@konghq.com
    name: Kong Inc
    url: https://konghq.com
  description: 'OpenAPI 3.0 spec for Kong Gateway''s Admin API.


    You can learn more about Kong Gateway at [developer.konghq.com](https://developer.konghq.com).

    Give Kong a star at the [Kong/kong](https://github.com/kong/kong) repository.'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Kong Enterprise Admin ACLs DP Certificates API
  version: 3.14.0
servers:
- description: Default Admin API URL
  url: '{protocol}://{hostname}:{port}{path}'
  variables:
    hostname:
      default: localhost
      description: Hostname for Kong's Admin API
    path:
      default: /
      description: Base path for Kong's Admin API
    port:
      default: '8001'
      description: Port for Kong's Admin API
    protocol:
      default: http
      description: Protocol for requests to Kong's Admin API
      enum:
      - http
      - https
security:
- adminToken: []
tags:
- description: DP Certificates
  name: DP Certificates
paths:
  /v2/control-planes/{controlPlaneId}/dp-client-certificates:
    parameters:
    - $ref: '#/components/parameters/controlPlaneId'
    get:
      operationId: list-dp-client-certificates
      summary: List DP Client Certificates
      description: Returns a list of pinned dataplane client certificates that are associated to this control plane. A pinned dataplane certificate allows dataplanes configured with the certificate and corresponding private key to establish connection with this control plane.
      responses:
        '200':
          $ref: '#/components/responses/ListDataPlaneCertificatesResponse'
        '401':
          $ref: '#/components/responses/KonnectCPLegacyUnauthorized'
        '403':
          $ref: '#/components/responses/KonnectCPLegacyForbidden'
        '404':
          $ref: '#/components/responses/KonnectCPLegacyNotFound'
      tags:
      - DP Certificates
    post:
      x-speakeasy-entity-operation:
        terraform-resource: GatewayDataPlaneClientCertificate#create
        terraform-datasource: null
      operationId: create-dataplane-certificate
      summary: Pin New DP Client Certificate
      description: Pin a new DP Client Certificate to this control plane. A pinned dataplane certificate allows dataplanes configured with the certificate and corresponding private key to establish connection with this control plane.
      requestBody:
        $ref: '#/components/requestBodies/DataPlaneClientCertificateRequest'
      responses:
        '201':
          $ref: '#/components/responses/DataPlaneClientCertificateResponse'
        '400':
          $ref: '#/components/responses/KonnectCPLegacyBadRequest'
        '401':
          $ref: '#/components/responses/KonnectCPLegacyUnauthorized'
        '403':
          $ref: '#/components/responses/KonnectCPLegacyForbidden'
        '404':
          $ref: '#/components/responses/KonnectCPLegacyNotFound'
      tags:
      - DP Certificates
  /v2/control-planes/{controlPlaneId}/dp-client-certificates/{certificateId}:
    parameters:
    - $ref: '#/components/parameters/controlPlaneId'
    - $ref: '#/components/parameters/DataPlaneCertificateId'
    get:
      x-speakeasy-entity-operation:
        terraform-resource: GatewayDataPlaneClientCertificate#read
        terraform-datasource: null
      operationId: get-dataplane-certificate
      summary: Get a DP Client Certificate
      description: Retrieve a pinned dataplane client certificate associated to this control plane. A pinned dataplane certificate allows dataplanes configured with the certificate and corresponding private key to establish connection with this control plane.
      responses:
        '200':
          $ref: '#/components/responses/DataPlaneClientCertificateResponse'
        '401':
          $ref: '#/components/responses/KonnectCPLegacyUnauthorized'
        '403':
          $ref: '#/components/responses/KonnectCPLegacyForbidden'
        '404':
          $ref: '#/components/responses/KonnectCPLegacyNotFound'
      tags:
      - DP Certificates
    put:
      x-speakeasy-entity-operation:
        terraform-resource: GatewayDataPlaneClientCertificate#update
        terraform-datasource: null
      operationId: update-dataplane-certificate
      summary: Update DP Client Certificate
      description: Update a DP Client Certificate for this control plane. A dataplane certificate allows dataplanes configured with the certificate and corresponding private key to establish connection with this control plane.
      requestBody:
        $ref: '#/components/requestBodies/DataPlaneClientCertificateRequest'
      responses:
        '200':
          $ref: '#/components/responses/DataPlaneClientCertificateResponse'
        '400':
          $ref: '#/components/responses/KonnectCPLegacyBadRequest'
        '401':
          $ref: '#/components/responses/KonnectCPLegacyUnauthorized'
        '403':
          $ref: '#/components/responses/KonnectCPLegacyForbidden'
        '404':
          $ref: '#/components/responses/KonnectCPLegacyNotFound'
      tags:
      - DP Certificates
    delete:
      x-speakeasy-entity-operation:
        terraform-resource: GatewayDataPlaneClientCertificate#delete
        terraform-datasource: null
      operationId: delete-dataplane-certificate
      summary: Delete DP Client Certificate
      description: Remove a pinned dataplane client certificate associated to this control plane. Removing a pinned dataplane certificate would invalidate any dataplanes currently connected to this control plane using this certificate.
      responses:
        '204':
          description: No Content
        '401':
          $ref: '#/components/responses/KonnectCPLegacyUnauthorized'
        '403':
          $ref: '#/components/responses/KonnectCPLegacyForbidden'
        '404':
          $ref: '#/components/responses/KonnectCPLegacyNotFound'
      tags:
      - DP Certificates
components:
  responses:
    KonnectCPLegacyForbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/KonnectCPLegacyForbiddenError'
    KonnectCPLegacyNotFound:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/KonnectCPLegacyNotFoundError'
    KonnectCPLegacyUnauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/KonnectCPLegacyUnauthorizedError'
    ListDataPlaneCertificatesResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              items:
                type: array
                items:
                  $ref: '#/components/schemas/DataPlaneClientCertificate'
              page:
                type: object
                properties:
                  total:
                    type: integer
    KonnectCPLegacyBadRequest:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/KonnectCPLegacyBadRequestError'
    DataPlaneClientCertificateResponse:
      description: Response body for retrieving a dp-client-certificate.
      content:
        application/json:
          schema:
            type: object
            properties:
              item:
                $ref: '#/components/schemas/DataPlaneClientCertificate'
  schemas:
    KonnectCPLegacyUnauthorizedError:
      allOf:
      - $ref: '#/components/schemas/KonnectCPLegacyBaseError'
      - type: object
        properties:
          message:
            example: Unauthorized
    KonnectCPLegacyNotFoundError:
      allOf:
      - $ref: '#/components/schemas/KonnectCPLegacyBaseError'
      - type: object
        properties:
          message:
            example: Not Found
    DataPlaneClientCertificate:
      x-speakeasy-entity: GatewayDataPlaneClientCertificate
      type: object
      properties:
        id:
          description: Unique ID of the certificate entity.
          type: string
        created_at:
          description: Date certificate was created.
          type: integer
        updated_at:
          description: Date certificate was last updated.
          type: integer
        cert:
          description: JSON escaped string of the certificate.
          type: string
        title:
          description: Title of the certificate.
          type: string
    KonnectCPLegacyBaseError:
      description: standard error
      type: object
      properties:
        message:
          description: 'A short summary of the problem.

            '
          type: string
          readOnly: true
      title: Error
    KonnectCPLegacyForbiddenError:
      allOf:
      - $ref: '#/components/schemas/KonnectCPLegacyBaseError'
      - type: object
        properties:
          message:
            example: Forbidden
    KonnectCPLegacyBadRequestError:
      allOf:
      - $ref: '#/components/schemas/KonnectCPLegacyBaseError'
      - type: object
        properties:
          message:
            example: Bad Request
  parameters:
    DataPlaneCertificateId:
      name: certificateId
      in: path
      schema:
        type: string
      required: true
      x-speakeasy-match: id
    controlPlaneId:
      name: controlPlaneId
      in: path
      required: true
      schema:
        type: string
        format: uuid
        example: 9524ec7d-36d9-465d-a8c5-83a3c9390458
      description: The UUID of your control plane. This variable is available in the Konnect manager.
      x-speakeasy-param-force-new: true
  requestBodies:
    DataPlaneClientCertificateRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              cert:
                description: JSON escaped string of the certificate.
                type: string
              title:
                description: Title for the certificate.
                type: string
            required:
            - cert
      description: Request body for creating a dp-client-certificate.
  securitySchemes:
    adminToken:
      in: header
      name: Kong-Admin-Token
      type: apiKey
externalDocs:
  description: Documentation for Kong Gateway and its APIs
  url: https://developer.konghq.com
