openapi: 3.1.0
info:
  contact:
    email: support@konghq.com
    name: Kong Inc
    url: https://konghq.com
  description: 'OpenAPI 3.0 spec for Kong Gateway''s Admin API.


    You can learn more about Kong Gateway at [developer.konghq.com](https://developer.konghq.com).

    Give Kong a star at the [Kong/kong](https://github.com/kong/kong) repository.'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Kong Enterprise Admin ACLs Assets API
  version: 3.14.0
servers:
- description: Default Admin API URL
  url: '{protocol}://{hostname}:{port}{path}'
  variables:
    hostname:
      default: localhost
      description: Hostname for Kong's Admin API
    path:
      default: /
      description: Base path for Kong's Admin API
    port:
      default: '8001'
      description: Port for Kong's Admin API
    protocol:
      default: http
      description: Protocol for requests to Kong's Admin API
      enum:
      - http
      - https
security:
- adminToken: []
tags:
- name: Assets
  description: APIs for managing static assets for Konnect Developer Portals.
paths:
  /v3/portals/{portalId}/assets/favicon:
    parameters:
    - $ref: '#/components/parameters/PortalId'
    get:
      x-speakeasy-entity-operation:
        terraform-resource: PortalFavicon#read
        terraform-datasource: null
      operationId: get-portal-asset-favicon
      summary: Get Favicon
      description: Returns the favicon of the portal.
      responses:
        '200':
          $ref: '#/components/responses/PortalAssetResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
      - Assets
    put:
      x-speakeasy-entity-operation:
        terraform-resource: PortalFavicon#create,update
        terraform-datasource: null
      operationId: replace-portal-asset-favicon
      summary: Replace Favicon
      description: Replaces the favicon of the portal. The favicon is used in the browser tab of the portal.
      requestBody:
        $ref: '#/components/requestBodies/ReplacePortalImageAsset'
      responses:
        '200':
          $ref: '#/components/responses/PortalAssetResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
      - Assets
  /v3/portals/{portalId}/assets/favicon/raw:
    parameters:
    - $ref: '#/components/parameters/PortalId'
    get:
      operationId: get-portal-asset-favicon-raw
      summary: Get Favicon (Raw)
      description: Returns the raw favicon of the portal.
      responses:
        '200':
          $ref: '#/components/responses/PortalAssetResponseRaw'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
      - Assets
  /v3/portals/{portalId}/assets/logo:
    parameters:
    - $ref: '#/components/parameters/PortalId'
    get:
      x-speakeasy-entity-operation:
        terraform-resource: PortalLogo#read
        terraform-datasource: null
      operationId: get-portal-asset-logo
      summary: Get Logo
      description: Returns the logo of the portal.
      responses:
        '200':
          $ref: '#/components/responses/PortalAssetResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
      - Assets
    put:
      x-speakeasy-entity-operation:
        terraform-resource: PortalLogo#create,update
        terraform-datasource: null
      operationId: replace-portal-asset-logo
      summary: Replace Logo
      description: Replaces the logo of the portal.
      requestBody:
        $ref: '#/components/requestBodies/ReplacePortalImageAsset'
      responses:
        '200':
          $ref: '#/components/responses/PortalAssetResponse'
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
      - Assets
  /v3/portals/{portalId}/assets/logo/raw:
    parameters:
    - $ref: '#/components/parameters/PortalId'
    get:
      operationId: get-portal-asset-logo-raw
      summary: Get Logo (Raw)
      description: Returns the raw logo of the portal.
      responses:
        '200':
          $ref: '#/components/responses/PortalAssetResponseRaw'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
      tags:
      - Assets
components:
  schemas:
    InvalidParameterMinimumLength:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
          - min_length
          - min_digits
          - min_lowercase
          - min_uppercase
          - min_symbols
          - min_items
          - min
          nullable: false
          readOnly: true
          x-speakeasy-unknown-values: allow
        minimum:
          type: integer
          example: 8
        source:
          type: string
          example: body
        reason:
          type: string
          example: must have at least 8 characters
          readOnly: true
      additionalProperties: false
      required:
      - field
      - reason
      - rule
      - minimum
    ImageICODataUri:
      description: must be a data URL with base64 ICO image data, e.g., data:image/ico;base64,<BASE64_IMAGE_DATA>
      type: string
      format: uri
      example: data:image/ico,YW5faW1hZ2VfZmlsZQ==
      pattern: ^data:image/(x-icon|ico|icon|vnd.microsoft.icon)(;base64)?,(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
      title: ImageICODataUri
      x-validation-message: must be a data URL with base64 ICO image data, e.g., data:image/ico;base64,<BASE64_IMAGE_DATA>
    InvalidParameterChoiceItem:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
          - enum
          nullable: false
          readOnly: true
        reason:
          type: string
          example: is a required field
          readOnly: true
        choices:
          type: array
          items: {}
          minItems: 1
          nullable: false
          readOnly: true
          uniqueItems: true
        source:
          type: string
          example: body
      additionalProperties: false
      required:
      - field
      - reason
      - rule
      - choices
    InvalidParameterMaximumLength:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
          - max_length
          - max_items
          - max
          nullable: false
          readOnly: true
          x-speakeasy-unknown-values: allow
        maximum:
          type: integer
          example: 8
        source:
          type: string
          example: body
        reason:
          type: string
          example: must not have more than 8 characters
          readOnly: true
      additionalProperties: false
      required:
      - field
      - reason
      - rule
      - maximum
    ImageGIFDataUri:
      description: must be a data URL with base64 GIF image data, e.g., data:image/gif;base64,<BASE64_IMAGE_DATA>
      type: string
      format: uri
      example: data:image/gif,YW5faW1hZ2VfZmlsZQ==
      pattern: ^data:image/gif(;base64)?,(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
      title: ImageGIFDataUri
      x-validation-message: must be a data URL with base64 GIF image data, e.g., data:image/gif;base64,<BASE64_IMAGE_DATA>
    ForbiddenError:
      allOf:
      - $ref: '#/components/schemas/BaseError'
      - type: object
        properties:
          status:
            example: 403
          title:
            example: Forbidden
          type:
            example: https://httpstatuses.com/403
          instance:
            example: kong:trace:1234567890
          detail:
            example: Forbidden
    UnauthorizedError:
      allOf:
      - $ref: '#/components/schemas/BaseError'
      - type: object
        properties:
          status:
            example: 401
          title:
            example: Unauthorized
          type:
            example: https://httpstatuses.com/401
          instance:
            example: kong:trace:1234567890
          detail:
            example: Invalid credentials
    ImageSVGDataUri:
      description: must be a data URL with base64 SVG image data, e.g., data:image/svg\+xml;base64,<BASE64_IMAGE_DATA>
      type: string
      format: uri
      example: data:image/svg+xml,YW5faW1hZ2VfZmlsZQ==
      pattern: ^data:image/svg\+xml(;base64)?,(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
      title: ImageSVGDataUri
      x-validation-message: must be a data URL with base64 SVG image data, e.g., data:image/svg\+xml;base64,<BASE64_IMAGE_DATA>
    ImageJPGDataUri:
      description: must be a data URL with base64 JPEG image data, e.g., data:image/jpeg;base64,<BASE64_IMAGE_DATA>
      type: string
      format: uri
      example: data:image/jpeg,YW5faW1hZ2VfZmlsZQ==
      pattern: ^data:image/jpeg(;base64)?,(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
      title: ImageJPGDataUri
      x-validation-message: must be a data URL with base64 JPEG image data, e.g., data:image/jpeg;base64,<BASE64_IMAGE_DATA>
    ImagePNGDataUri:
      description: must be a data URL with base64 PNG image data, e.g., data:image/png;base64,<BASE64_IMAGE_DATA>
      type: string
      format: uri
      example: data:image/png,YW5faW1hZ2VfZmlsZQ==
      pattern: ^data:image/png(;base64)?,(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
      title: ImagePNGDataUri
      x-validation-message: must be a data URL with base64 PNG image data, e.g., data:image/png;base64,<BASE64_IMAGE_DATA>
    ReplacePortalImageAsset:
      description: The image data to upload. Images must be a data URL with binary image data in base 64 format. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs.
      type: object
      properties:
        data:
          $ref: '#/components/schemas/PortalImageDataUri'
      example:
        data: data:image/jpeg;base64,bmljZV9sb29raW5nX3BpY3R1cmU=
      additionalProperties: false
      nullable: true
      required:
      - data
      title: ReplacePortalImageAsset
    BaseError:
      description: standard error
      type: object
      properties:
        status:
          description: 'The HTTP status code of the error. Useful when passing the response

            body to child properties in a frontend UI. Must be returned as an integer.

            '
          type: integer
          readOnly: true
        title:
          description: 'A short, human-readable summary of the problem. It should not

            change between occurences of a problem, except for localization.

            Should be provided as "Sentence case" for direct use in the UI.

            '
          type: string
          readOnly: true
        type:
          description: The error type.
          type: string
          readOnly: true
        instance:
          description: 'Used to return the correlation ID back to the user, in the format

            kong:trace:<correlation_id>. This helps us find the relevant logs

            when a customer reports an issue.

            '
          type: string
          readOnly: true
        detail:
          description: 'A human readable explanation specific to this occurence of the problem.

            This field may contain request/entity data to help the user understand

            what went wrong. Enclose variable values in square brackets. Should be

            provided as "Sentence case" for direct use in the UI.

            '
          type: string
          readOnly: true
      required:
      - status
      - title
      - instance
      - detail
      title: Error
    InvalidParameterDependentItem:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
          - dependent_fields
          nullable: true
          readOnly: true
        reason:
          type: string
          example: is a required field
          readOnly: true
        dependents:
          type: array
          items: {}
          nullable: true
          readOnly: true
          uniqueItems: true
        source:
          type: string
          example: body
      additionalProperties: false
      required:
      - field
      - rule
      - reason
      - dependents
    InvalidRules:
      description: invalid parameters rules
      type: string
      enum:
      - required
      - is_array
      - is_base64
      - is_boolean
      - is_date_time
      - is_integer
      - is_null
      - is_number
      - is_object
      - is_string
      - is_uuid
      - is_fqdn
      - is_arn
      - unknown_property
      - missing_reference
      - is_label
      - matches_regex
      - invalid
      - is_supported_network_availability_zone_list
      - is_supported_network_cidr_block
      - is_supported_provider_region
      - type
      nullable: true
      readOnly: true
      x-speakeasy-unknown-values: allow
    InvalidParameters:
      description: invalid parameters
      type: array
      items:
        oneOf:
        - $ref: '#/components/schemas/InvalidParameterStandard'
        - $ref: '#/components/schemas/InvalidParameterMinimumLength'
        - $ref: '#/components/schemas/InvalidParameterMaximumLength'
        - $ref: '#/components/schemas/InvalidParameterChoiceItem'
        - $ref: '#/components/schemas/InvalidParameterDependentItem'
      minItems: 1
      nullable: false
      uniqueItems: true
    BadRequestError:
      allOf:
      - $ref: '#/components/schemas/BaseError'
      - type: object
        required:
        - invalid_parameters
        properties:
          invalid_parameters:
            $ref: '#/components/schemas/InvalidParameters'
    PortalImageAssetBlob:
      description: Raw binary image data
      type: string
      format: binary
      title: PortalImageAsset
    InvalidParameterStandard:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          $ref: '#/components/schemas/InvalidRules'
        source:
          type: string
          example: body
        reason:
          type: string
          example: is a required field
          readOnly: true
      additionalProperties: false
      required:
      - field
      - reason
    PortalImageDataUri:
      oneOf:
      - $ref: '#/components/schemas/ImagePNGDataUri'
      - $ref: '#/components/schemas/ImageJPGDataUri'
      - $ref: '#/components/schemas/ImageGIFDataUri'
      - $ref: '#/components/schemas/ImageICODataUri'
      - $ref: '#/components/schemas/ImageSVGDataUri'
      title: PortalImageDataUri
  responses:
    PortalAssetResponse:
      description: Image asset for the portal. Can be either png, jpeg or svg
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: '#/components/schemas/PortalImageDataUri'
            additionalProperties: false
            required:
            - data
    Unauthorized:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            description: The error response object.
            type: object
            properties:
              status:
                description: The HTTP status code.
                type: integer
                example: 403
              title:
                description: The Error Response.
                type: string
                example: Unauthorized
              instance:
                description: The Konnect traceback code.
                type: string
                example: konnect:trace:952172606039454040
              detail:
                description: Details about the error response.
                type: string
                example: You do not have permission to perform this action
            $ref: '#/components/schemas/UnauthorizedError'
            title: Unauthorized Response
    PortalAssetResponseRaw:
      description: Logo of the portal. Can be either png, jpeg or svg
      content:
        image/jpeg:
          schema:
            $ref: '#/components/schemas/PortalImageAssetBlob'
        image/png:
          schema:
            $ref: '#/components/schemas/PortalImageAssetBlob'
        image/svg+xml:
          schema:
            $ref: '#/components/schemas/PortalImageAssetBlob'
    Forbidden:
      description: Forbidden
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ForbiddenError'
  requestBodies:
    ReplacePortalImageAsset:
      description: Update an image asset for the portal.
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ReplacePortalImageAsset'
  parameters:
    PortalId:
      schema:
        type: string
        format: uuid
        example: f32d905a-ed33-46a3-a093-d8f536af9a8a
      name: portalId
      in: path
      required: true
      description: ID of the portal.
  securitySchemes:
    adminToken:
      in: header
      name: Kong-Admin-Token
      type: apiKey
externalDocs:
  description: Documentation for Kong Gateway and its APIs
  url: https://developer.konghq.com
