openapi: 3.1.0
info:
  contact:
    email: support@konghq.com
    name: Kong Inc
    url: https://konghq.com
  description: 'OpenAPI 3.0 spec for Kong Gateway''s Admin API.


    You can learn more about Kong Gateway at [developer.konghq.com](https://developer.konghq.com).

    Give Kong a star at the [Kong/kong](https://github.com/kong/kong) repository.'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Kong Enterprise Admin ACLs GraphQL Cost Decorations API
  version: 3.14.0
servers:
- description: Default Admin API URL
  url: '{protocol}://{hostname}:{port}{path}'
  variables:
    hostname:
      default: localhost
      description: Hostname for Kong's Admin API
    path:
      default: /
      description: Base path for Kong's Admin API
    port:
      default: '8001'
      description: Port for Kong's Admin API
    protocol:
      default: http
      description: Protocol for requests to Kong's Admin API
      enum:
      - http
      - https
security:
- adminToken: []
tags:
- name: GraphQL Cost Decorations
paths:
  /v2/control-planes/{controlPlaneId}/core-entities/graphql-rate-limiting-advanced/costs:
    parameters:
    - $ref: '#/components/parameters/controlPlaneId'
    get:
      operationId: list-graphql-rate-limiting-advanced-cost
      summary: List all GraphQL Cost Decorations
      description: List all GraphQL Cost Decorations
      parameters:
      - $ref: '#/components/parameters/PaginationSize'
      - $ref: '#/components/parameters/PaginationOffset'
      - $ref: '#/components/parameters/PaginationTagsFilter'
      responses:
        '200':
          description: A successful response listing GraphQL Cost Decorations
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/GraphQLCostDecoration'
                  next:
                    $ref: '#/components/schemas/PaginationNextResponse'
                  offset:
                    $ref: '#/components/schemas/PaginationOffsetResponse'
        '401':
          $ref: '#/components/responses/HTTP401Error'
      tags:
      - GraphQL Cost Decorations
  /v2/control-planes/{controlPlaneId}/core-entities/graphql-rate-limiting-advanced/costs/{GraphQLCostDecorationId}:
    parameters:
    - $ref: '#/components/parameters/GraphQLCostDecorationId'
    - $ref: '#/components/parameters/controlPlaneId'
    get:
      operationId: get-graphql-rate-limiting-advanced-cost
      summary: Get a GraphQL Cost Decoration
      description: Get a GraphQL Cost Decoration using ID.
      responses:
        '200':
          description: Successfully fetched GraphQL Cost Decoration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GraphQLCostDecoration'
        '401':
          $ref: '#/components/responses/HTTP401Error'
        '404':
          description: Resource does not exist
      tags:
      - GraphQL Cost Decorations
  /v2/control-planes/{controlPlaneId}/core-entities/services/{ServiceId}/graphql-rate-limiting-advanced/costs:
    parameters:
    - $ref: '#/components/parameters/controlPlaneId'
    get:
      operationId: list-graphql-rate-limiting-advanced-cost-with-service
      summary: List all GraphQL Cost Decorations associated with a Service
      description: List all GraphQL Cost Decorations associated with a Service
      parameters:
      - $ref: '#/components/parameters/ServiceId'
      - $ref: '#/components/parameters/PaginationSize'
      - $ref: '#/components/parameters/PaginationOffset'
      - $ref: '#/components/parameters/PaginationTagsFilter'
      responses:
        '200':
          description: A successful response listing GraphQL Cost Decorations
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/GraphQLCostDecoration'
                  next:
                    $ref: '#/components/schemas/PaginationNextResponse'
                  offset:
                    $ref: '#/components/schemas/PaginationOffsetResponse'
      tags:
      - GraphQL Cost Decorations
    post:
      operationId: create-graphql-rate-limiting-advanced-cost-with-service
      summary: Create a new GraphQL Cost Decoration associated with a Service
      description: Create a new GraphQL Cost Decoration associated with a Service
      parameters:
      - $ref: '#/components/parameters/ServiceId'
      requestBody:
        description: Description of new GraphQL Cost Decoration for creation
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GraphQLCostDecorationWithoutParents'
      responses:
        '201':
          description: Successfully created GraphQL Cost Decoration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GraphQLCostDecoration'
      tags:
      - GraphQL Cost Decorations
  ? /v2/control-planes/{controlPlaneId}/core-entities/services/{ServiceId}/graphql-rate-limiting-advanced/costs/{GraphQLCostDecorationId}
  : parameters:
    - $ref: '#/components/parameters/controlPlaneId'
    delete:
      operationId: delete-graphql-rate-limiting-advanced-cost-with-service
      summary: Delete a a GraphQL Cost Decoration associated with a Service
      description: Delete a a GraphQL Cost Decoration associated with a Service using ID.
      parameters:
      - $ref: '#/components/parameters/ServiceId'
      - $ref: '#/components/parameters/GraphQLCostDecorationId'
      responses:
        '204':
          description: Successfully deleted GraphQL Cost Decoration or the resource didn't exist
      tags:
      - GraphQL Cost Decorations
    get:
      operationId: get-graphql-rate-limiting-advanced-cost-with-service
      summary: Get a GraphQL Cost Decoration associated with a Service
      description: Get a GraphQL Cost Decoration associated with a Service using ID.
      parameters:
      - $ref: '#/components/parameters/ServiceId'
      - $ref: '#/components/parameters/GraphQLCostDecorationId'
      responses:
        '200':
          description: Successfully fetched GraphQL Cost Decoration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GraphQLCostDecoration'
        '404':
          description: Resource does not exist
      tags:
      - GraphQL Cost Decorations
    put:
      operationId: upsert-graphql-rate-limiting-advanced-cost-with-service
      summary: Upsert a GraphQL Cost Decoration associated with a Service
      description: Create or Update a GraphQL Cost Decoration associated with a Service using ID.
      parameters:
      - $ref: '#/components/parameters/ServiceId'
      - $ref: '#/components/parameters/GraphQLCostDecorationId'
      requestBody:
        description: Description of the GraphQL Cost Decoration
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GraphQLCostDecorationWithoutParents'
      responses:
        '200':
          description: Successfully upserted GraphQL Cost Decoration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GraphQLCostDecoration'
      tags:
      - GraphQL Cost Decorations
components:
  parameters:
    GraphQLCostDecorationId:
      description: ID of the GraphQL Cost Decoration to lookup
      example: ''
      in: path
      name: GraphQLCostDecorationId
      required: true
      schema:
        type: string
    PaginationSize:
      description: Number of resources to be returned.
      in: query
      name: size
      schema:
        type: integer
        default: 100
        maximum: 1000
        minimum: 1
    ServiceId:
      description: ID of the Service to lookup
      example: 7fca84d6-7d37-4a74-a7b0-93e576089a41
      in: path
      name: ServiceId
      required: true
      schema:
        type: string
    PaginationOffset:
      allowEmptyValue: true
      description: Offset from which to return the next set of resources. Use the value of the 'offset' field from the response of a list operation as input here to paginate through all the resources
      in: query
      name: offset
      schema:
        type: string
    controlPlaneId:
      name: controlPlaneId
      in: path
      required: true
      schema:
        type: string
        format: uuid
        example: 9524ec7d-36d9-465d-a8c5-83a3c9390458
      description: The UUID of your control plane. This variable is available in the Konnect manager.
      x-speakeasy-param-force-new: true
    PaginationTagsFilter:
      allowEmptyValue: true
      description: A list of tags to filter the list of resources on. Multiple tags can be concatenated using ',' to mean AND or using '/' to mean OR.
      example: tag1,tag2
      in: query
      name: tags
      schema:
        type: string
  schemas:
    PaginationOffsetResponse:
      description: Offset is used to paginate through the API. Provide this value to the next list operation to fetch the next page
      type: string
    GatewayUnauthorizedError:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
      required:
      - message
      - status
    GraphQLCostDecoration:
      type: object
      properties:
        add_arguments:
          type: array
          items:
            type: string
          default: []
          nullable: true
        add_constant:
          type: number
          default: 1
          nullable: true
        created_at:
          description: Unix epoch when the resource was created.
          type: integer
          nullable: true
        id:
          description: A string representing a UUID (universally unique identifier).
          type: string
          nullable: true
        mul_arguments:
          type: array
          items:
            type: string
          default: []
          nullable: true
        mul_constant:
          type: number
          default: 1
          nullable: true
        service:
          type: object
          nullable: true
          properties:
            id:
              type: string
          x-foreign: true
        type_path:
          type: string
      additionalProperties: false
      required:
      - type_path
    GraphQLCostDecorationWithoutParents:
      type: object
      properties:
        add_arguments:
          type: array
          items:
            type: string
          default: []
          nullable: true
        add_constant:
          type: number
          default: 1
          nullable: true
        created_at:
          description: Unix epoch when the resource was created.
          type: integer
          nullable: true
        id:
          description: A string representing a UUID (universally unique identifier).
          type: string
          nullable: true
        mul_arguments:
          type: array
          items:
            type: string
          default: []
          nullable: true
        mul_constant:
          type: number
          default: 1
          nullable: true
        service:
          type: object
          nullable: true
          properties:
            id:
              type: string
          x-foreign: true
        type_path:
          type: string
      additionalProperties: false
      required:
      - type_path
    PaginationNextResponse:
      description: URI to the next page (may be null)
      type: string
  responses:
    HTTP401Error:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GatewayUnauthorizedError'
  securitySchemes:
    adminToken:
      in: header
      name: Kong-Admin-Token
      type: apiKey
externalDocs:
  description: Documentation for Kong Gateway and its APIs
  url: https://developer.konghq.com
