openapi: 3.1.0
info:
  contact:
    email: support@konghq.com
    name: Kong Inc
    url: https://konghq.com
  description: 'OpenAPI 3.0 spec for Kong Gateway''s Admin API.


    You can learn more about Kong Gateway at [developer.konghq.com](https://developer.konghq.com).

    Give Kong a star at the [Kong/kong](https://github.com/kong/kong) repository.'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Kong Enterprise Admin ACLs Degraphql_routes API
  version: 3.14.0
servers:
- description: Default Admin API URL
  url: '{protocol}://{hostname}:{port}{path}'
  variables:
    hostname:
      default: localhost
      description: Hostname for Kong's Admin API
    path:
      default: /
      description: Base path for Kong's Admin API
    port:
      default: '8001'
      description: Port for Kong's Admin API
    protocol:
      default: http
      description: Protocol for requests to Kong's Admin API
      enum:
      - http
      - https
security:
- adminToken: []
tags:
- name: Degraphql_routes
paths:
  /v2/control-planes/{controlPlaneId}/core-entities/degraphql_routes:
    parameters:
    - $ref: '#/components/parameters/controlPlaneId'
    get:
      operationId: list-degraphql_route
      summary: List all Degraphql_routes
      description: List all Degraphql_routes
      parameters:
      - $ref: '#/components/parameters/PaginationSize'
      - $ref: '#/components/parameters/PaginationOffset'
      - $ref: '#/components/parameters/PaginationTagsFilter'
      responses:
        '200':
          description: A successful response listing Degraphql_routes
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Degraphql_route'
                  next:
                    $ref: '#/components/schemas/PaginationNextResponse'
                  offset:
                    $ref: '#/components/schemas/PaginationOffsetResponse'
        '401':
          $ref: '#/components/responses/HTTP401Error'
      tags:
      - Degraphql_routes
  /v2/control-planes/{controlPlaneId}/core-entities/degraphql_routes/{Degraphql_routeId}:
    parameters:
    - $ref: '#/components/parameters/Degraphql_routeId'
    - $ref: '#/components/parameters/controlPlaneId'
    get:
      operationId: get-degraphql_route
      summary: Get a Degraphql_route
      description: Get a Degraphql_route using ID or name.
      responses:
        '200':
          description: Successfully fetched Degraphql_route
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Degraphql_route'
        '401':
          $ref: '#/components/responses/HTTP401Error'
        '404':
          description: Resource does not exist
      tags:
      - Degraphql_routes
  /v2/control-planes/{controlPlaneId}/core-entities/services/{ServiceId}/degraphql/routes:
    parameters:
    - $ref: '#/components/parameters/controlPlaneId'
    get:
      operationId: list-degraphql_route-with-service
      summary: List all Degraphql_routes associated with a Service
      description: List all Degraphql_routes associated with a Service
      parameters:
      - $ref: '#/components/parameters/ServiceId'
      - $ref: '#/components/parameters/PaginationSize'
      - $ref: '#/components/parameters/PaginationOffset'
      - $ref: '#/components/parameters/PaginationTagsFilter'
      responses:
        '200':
          description: A successful response listing Degraphql_routes
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Degraphql_route'
                  next:
                    $ref: '#/components/schemas/PaginationNextResponse'
                  offset:
                    $ref: '#/components/schemas/PaginationOffsetResponse'
      tags:
      - Degraphql_routes
    post:
      operationId: create-degraphql_route-with-service
      summary: Create a new Degraphql_route associated with a Service
      description: Create a new Degraphql_route associated with a Service
      parameters:
      - $ref: '#/components/parameters/ServiceId'
      requestBody:
        description: Description of new Degraphql_route for creation
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Degraphql_routeWithoutParents'
      responses:
        '201':
          description: Successfully created Degraphql_route
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Degraphql_route'
      tags:
      - Degraphql_routes
  /v2/control-planes/{controlPlaneId}/core-entities/services/{ServiceId}/degraphql/routes/{Degraphql_routeId}:
    parameters:
    - $ref: '#/components/parameters/controlPlaneId'
    delete:
      operationId: delete-degraphql_route-with-service
      summary: Delete a a Degraphql_route associated with a Service
      description: Delete a a Degraphql_route associated with a Service using ID or name.
      parameters:
      - $ref: '#/components/parameters/ServiceId'
      - $ref: '#/components/parameters/Degraphql_routeId'
      responses:
        '204':
          description: Successfully deleted Degraphql_route or the resource didn't exist
      tags:
      - Degraphql_routes
    get:
      operationId: get-degraphql_route-with-service
      summary: Get a Degraphql_route associated with a Service
      description: Get a Degraphql_route associated with a Service using ID or name.
      parameters:
      - $ref: '#/components/parameters/ServiceId'
      - $ref: '#/components/parameters/Degraphql_routeId'
      responses:
        '200':
          description: Successfully fetched Degraphql_route
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Degraphql_route'
        '404':
          description: Resource does not exist
      tags:
      - Degraphql_routes
    put:
      operationId: upsert-degraphql_route-with-service
      summary: Upsert a Degraphql_route associated with a Service
      description: Create or Update a Degraphql_route associated with a Service using ID or name.
      parameters:
      - $ref: '#/components/parameters/ServiceId'
      - $ref: '#/components/parameters/Degraphql_routeId'
      requestBody:
        description: Description of the Degraphql_route
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Degraphql_routeWithoutParents'
      responses:
        '200':
          description: Successfully upserted Degraphql_route
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Degraphql_route'
      tags:
      - Degraphql_routes
components:
  schemas:
    Degraphql_routeWithoutParents:
      type: object
      properties:
        created_at:
          description: Unix epoch when the resource was created.
          type: integer
          nullable: true
        id:
          description: A string representing a UUID (universally unique identifier).
          type: string
          nullable: true
        methods:
          type: array
          items:
            description: A string representing an HTTP method, such as GET, POST, PUT, or DELETE. The string must contain only uppercase letters.
            type: string
          default:
          - GET
          nullable: true
        query:
          type: string
        service:
          type: object
          properties:
            id:
              type: string
          x-foreign: true
        updated_at:
          description: Unix epoch when the resource was last updated.
          type: integer
          nullable: true
        uri:
          type: string
      example:
        id: 56c4566c-14cc-4132-9011-4139fcbbe50a
        query: query{ user { email } }
        uri: /users
      additionalProperties: false
      required:
      - query
      - uri
    PaginationOffsetResponse:
      description: Offset is used to paginate through the API. Provide this value to the next list operation to fetch the next page
      type: string
    GatewayUnauthorizedError:
      type: object
      properties:
        message:
          type: string
        status:
          type: integer
      required:
      - message
      - status
    Degraphql_route:
      type: object
      properties:
        created_at:
          description: Unix epoch when the resource was created.
          type: integer
          nullable: true
        id:
          description: A string representing a UUID (universally unique identifier).
          type: string
          nullable: true
        methods:
          type: array
          items:
            description: A string representing an HTTP method, such as GET, POST, PUT, or DELETE. The string must contain only uppercase letters.
            type: string
          default:
          - GET
          nullable: true
        query:
          type: string
        service:
          type: object
          properties:
            id:
              type: string
          x-foreign: true
        updated_at:
          description: Unix epoch when the resource was last updated.
          type: integer
          nullable: true
        uri:
          type: string
      example:
        id: 56c4566c-14cc-4132-9011-4139fcbbe50a
        query: query{ user { email } }
        service:
          id: bd380f99-659d-415e-b0e7-72ea05df3218
        uri: /users
      additionalProperties: false
      required:
      - query
      - uri
      - service
    PaginationNextResponse:
      description: URI to the next page (may be null)
      type: string
  parameters:
    PaginationSize:
      description: Number of resources to be returned.
      in: query
      name: size
      schema:
        type: integer
        default: 100
        maximum: 1000
        minimum: 1
    Degraphql_routeId:
      description: ID of the Degraphql_route to lookup
      example: ''
      in: path
      name: Degraphql_routeId
      required: true
      schema:
        type: string
    ServiceId:
      description: ID of the Service to lookup
      example: 7fca84d6-7d37-4a74-a7b0-93e576089a41
      in: path
      name: ServiceId
      required: true
      schema:
        type: string
    PaginationOffset:
      allowEmptyValue: true
      description: Offset from which to return the next set of resources. Use the value of the 'offset' field from the response of a list operation as input here to paginate through all the resources
      in: query
      name: offset
      schema:
        type: string
    controlPlaneId:
      name: controlPlaneId
      in: path
      required: true
      schema:
        type: string
        format: uuid
        example: 9524ec7d-36d9-465d-a8c5-83a3c9390458
      description: The UUID of your control plane. This variable is available in the Konnect manager.
      x-speakeasy-param-force-new: true
    PaginationTagsFilter:
      allowEmptyValue: true
      description: A list of tags to filter the list of resources on. Multiple tags can be concatenated using ',' to mean AND or using '/' to mean OR.
      example: tag1,tag2
      in: query
      name: tags
      schema:
        type: string
  responses:
    HTTP401Error:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GatewayUnauthorizedError'
  securitySchemes:
    adminToken:
      in: header
      name: Kong-Admin-Token
      type: apiKey
externalDocs:
  description: Documentation for Kong Gateway and its APIs
  url: https://developer.konghq.com
