openapi: 3.1.0
info:
  contact:
    email: support@konghq.com
    name: Kong Inc
    url: https://konghq.com
  description: 'OpenAPI 3.0 spec for Kong Gateway''s Admin API.


    You can learn more about Kong Gateway at [developer.konghq.com](https://developer.konghq.com).

    Give Kong a star at the [Kong/kong](https://github.com/kong/kong) repository.'
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Kong Enterprise Admin ACLs Integration Instance Auth Config API
  version: 3.14.0
servers:
- description: Default Admin API URL
  url: '{protocol}://{hostname}:{port}{path}'
  variables:
    hostname:
      default: localhost
      description: Hostname for Kong's Admin API
    path:
      default: /
      description: Base path for Kong's Admin API
    port:
      default: '8001'
      description: Port for Kong's Admin API
    protocol:
      default: http
      description: Protocol for requests to Kong's Admin API
      enum:
      - http
      - https
security:
- adminToken: []
tags:
- name: Integration Instance Auth Config
  description: 'A integration instance may need to be provided with an auth config before authorizing the instance.

    Typically an auth config will be required when authorizing against a integration which is hosted within your organization.

    The integration instance''s auth config will inform how the Service Catalog will authorize the integration instance.

    Note that updating the auth config for an instance which is already authorized will **remove the existing credential**, requiring you to re-authorize the instance.

    '
paths:
  /v1/integration-instances/{integrationInstanceId}/auth-config:
    parameters:
    - name: integrationInstanceId
      in: path
      description: The `id` of the integration instance.
      required: true
      schema:
        type: string
        example: 3f51fa25-310a-421d-bd1a-007f859021a3
    get:
      x-speakeasy-entity-operation:
        terraform-resource: IntegrationInstanceAuthConfig#read
        terraform-datasource: null
      operationId: get-integration-instance-auth-config
      summary: Get Integration Instance Auth Config
      description: Fetches auth config scoped to the given integration instance.
      responses:
        '200':
          $ref: '#/components/responses/IntegrationInstanceAuthConfigResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
      - Integration Instance Auth Config
    put:
      x-speakeasy-entity-operation: IntegrationInstanceAuthConfig#create,update
      operationId: upsert-integration-instance-auth-config
      summary: Upsert Integration Instance Auth Config
      description: Upserts auth config scoped to the given integration instance.
      requestBody:
        $ref: '#/components/requestBodies/UpsertIntegrationInstanceAuthConfigRequest'
      responses:
        '200':
          $ref: '#/components/responses/IntegrationInstanceAuthConfigResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
      - Integration Instance Auth Config
    delete:
      x-speakeasy-entity-operation: IntegrationInstanceAuthConfig#delete
      operationId: delete-integration-instance-auth-config
      summary: Delete Integration Instance Auth Config
      description: Deletes the auth config scoped to the given integration instance.
      responses:
        '204':
          description: Integration Instance Auth Config was deleted successfully.
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
      - Integration Instance Auth Config
components:
  schemas:
    InvalidParameterMinimumLength:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
          - min_length
          - min_digits
          - min_lowercase
          - min_uppercase
          - min_symbols
          - min_items
          - min
          nullable: false
          readOnly: true
          x-speakeasy-unknown-values: allow
        minimum:
          type: integer
          example: 8
        source:
          type: string
          example: body
        reason:
          type: string
          example: must have at least 8 characters
          readOnly: true
      additionalProperties: false
      required:
      - field
      - reason
      - rule
      - minimum
    InvalidParameterChoiceItem:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
          - enum
          nullable: false
          readOnly: true
        reason:
          type: string
          example: is a required field
          readOnly: true
        choices:
          type: array
          items: {}
          minItems: 1
          nullable: false
          readOnly: true
          uniqueItems: true
        source:
          type: string
          example: body
      additionalProperties: false
      required:
      - field
      - reason
      - rule
      - choices
    InvalidParameterMaximumLength:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
          - max_length
          - max_items
          - max
          nullable: false
          readOnly: true
          x-speakeasy-unknown-values: allow
        maximum:
          type: integer
          example: 8
        source:
          type: string
          example: body
        reason:
          type: string
          example: must not have more than 8 characters
          readOnly: true
      additionalProperties: false
      required:
      - field
      - reason
      - rule
      - maximum
    ForbiddenError:
      allOf:
      - $ref: '#/components/schemas/BaseError'
      - type: object
        properties:
          status:
            example: 403
          title:
            example: Forbidden
          type:
            example: https://httpstatuses.com/403
          instance:
            example: kong:trace:1234567890
          detail:
            example: Forbidden
    UnauthorizedError:
      allOf:
      - $ref: '#/components/schemas/BaseError'
      - type: object
        properties:
          status:
            example: 401
          title:
            example: Unauthorized
          type:
            example: https://httpstatuses.com/401
          instance:
            example: kong:trace:1234567890
          detail:
            example: Invalid credentials
    UpsertOAuthAuthConfig:
      type: object
      properties:
        type:
          type: string
          const: oauth
        client_id:
          description: The OAuth client identifier.
          type: string
          example: d745213a-b7e8-4998-abe3-41f164001970
        client_secret:
          description: The OAuth client secret.
          type: string
          example: s3cr3t4p1cl13ntt0k3n1234567890abcdef
          writeOnly: true
        authorization_endpoint:
          description: The URL where users are redirected to authorize access.
          type: string
          format: uri
          example: https://identity.service.com/oauth/authorize
        token_endpoint:
          description: The URL used to retrieve access tokens.
          type: string
          format: uri
          example: https://identity.service.com/oauth/token
      additionalProperties: false
      required:
      - type
      - client_id
      - client_secret
      - authorization_endpoint
      - token_endpoint
      title: OAuth Config
      x-speakeasy-name-override: oauth_config
    UpsertIntegrationInstanceAuthConfig:
      oneOf:
      - $ref: '#/components/schemas/UpsertOAuthAuthConfig'
      title: UpsertIntegrationInstanceAuthConfig
    BaseError:
      description: standard error
      type: object
      properties:
        status:
          description: 'The HTTP status code of the error. Useful when passing the response

            body to child properties in a frontend UI. Must be returned as an integer.

            '
          type: integer
          readOnly: true
        title:
          description: 'A short, human-readable summary of the problem. It should not

            change between occurences of a problem, except for localization.

            Should be provided as "Sentence case" for direct use in the UI.

            '
          type: string
          readOnly: true
        type:
          description: The error type.
          type: string
          readOnly: true
        instance:
          description: 'Used to return the correlation ID back to the user, in the format

            kong:trace:<correlation_id>. This helps us find the relevant logs

            when a customer reports an issue.

            '
          type: string
          readOnly: true
        detail:
          description: 'A human readable explanation specific to this occurence of the problem.

            This field may contain request/entity data to help the user understand

            what went wrong. Enclose variable values in square brackets. Should be

            provided as "Sentence case" for direct use in the UI.

            '
          type: string
          readOnly: true
      required:
      - status
      - title
      - instance
      - detail
      title: Error
    InvalidParameterDependentItem:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          description: invalid parameters rules
          type: string
          enum:
          - dependent_fields
          nullable: true
          readOnly: true
        reason:
          type: string
          example: is a required field
          readOnly: true
        dependents:
          type: array
          items: {}
          nullable: true
          readOnly: true
          uniqueItems: true
        source:
          type: string
          example: body
      additionalProperties: false
      required:
      - field
      - rule
      - reason
      - dependents
    InvalidRules:
      description: invalid parameters rules
      type: string
      enum:
      - required
      - is_array
      - is_base64
      - is_boolean
      - is_date_time
      - is_integer
      - is_null
      - is_number
      - is_object
      - is_string
      - is_uuid
      - is_fqdn
      - is_arn
      - unknown_property
      - missing_reference
      - is_label
      - matches_regex
      - invalid
      - is_supported_network_availability_zone_list
      - is_supported_network_cidr_block
      - is_supported_provider_region
      - type
      nullable: true
      readOnly: true
      x-speakeasy-unknown-values: allow
    OAuthAuthConfig:
      type: object
      properties:
        type:
          type: string
          const: oauth
        client_id:
          description: The OAuth client identifier.
          type: string
          example: d745213a-b7e8-4998-abe3-41f164001970
        authorization_endpoint:
          description: The URL where users are redirected to authorize access.
          type: string
          format: uri
          example: https://identity.service.com/oauth/authorize
        token_endpoint:
          description: The URL used to retrieve access tokens.
          type: string
          format: uri
          example: https://identity.service.com/oauth/token
      required:
      - type
      - client_id
      - authorization_endpoint
      - token_endpoint
      x-speakeasy-name-override: OauthAuthConfig
    InvalidParameters:
      description: invalid parameters
      type: array
      items:
        oneOf:
        - $ref: '#/components/schemas/InvalidParameterStandard'
        - $ref: '#/components/schemas/InvalidParameterMinimumLength'
        - $ref: '#/components/schemas/InvalidParameterMaximumLength'
        - $ref: '#/components/schemas/InvalidParameterChoiceItem'
        - $ref: '#/components/schemas/InvalidParameterDependentItem'
      minItems: 1
      nullable: false
      uniqueItems: true
    BadRequestError:
      allOf:
      - $ref: '#/components/schemas/BaseError'
      - type: object
        required:
        - invalid_parameters
        properties:
          invalid_parameters:
            $ref: '#/components/schemas/InvalidParameters'
    InvalidParameterStandard:
      type: object
      properties:
        field:
          type: string
          example: name
          readOnly: true
        rule:
          $ref: '#/components/schemas/InvalidRules'
        source:
          type: string
          example: body
        reason:
          type: string
          example: is a required field
          readOnly: true
      additionalProperties: false
      required:
      - field
      - reason
    NotFoundError:
      allOf:
      - $ref: '#/components/schemas/BaseError'
      - type: object
        properties:
          status:
            example: 404
          title:
            example: Not Found
          type:
            example: https://httpstatuses.com/404
          instance:
            example: kong:trace:1234567890
          detail:
            example: Not found
    IntegrationInstanceAuthConfig:
      oneOf:
      - $ref: '#/components/schemas/OAuthAuthConfig'
      title: IntegrationInstanceAuthConfig
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/BadRequestError'
    NotFound:
      description: Not Found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/NotFoundError'
    Unauthorized:
      description: Unauthorized
      content:
        application/problem+json:
          schema:
            description: The error response object.
            type: object
            properties:
              status:
                description: The HTTP status code.
                type: integer
                example: 403
              title:
                description: The Error Response.
                type: string
                example: Unauthorized
              instance:
                description: The Konnect traceback code.
                type: string
                example: konnect:trace:952172606039454040
              detail:
                description: Details about the error response.
                type: string
                example: You do not have permission to perform this action
            $ref: '#/components/schemas/UnauthorizedError'
            title: Unauthorized Response
    IntegrationInstanceAuthConfigResponse:
      description: A response containing integration instance auth config.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/IntegrationInstanceAuthConfig'
    Forbidden:
      description: Forbidden
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ForbiddenError'
  requestBodies:
    UpsertIntegrationInstanceAuthConfigRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpsertIntegrationInstanceAuthConfig'
  securitySchemes:
    adminToken:
      in: header
      name: Kong-Admin-Token
      type: apiKey
externalDocs:
  description: Documentation for Kong Gateway and its APIs
  url: https://developer.konghq.com
